[2022-07-12 15:28:48,998: WARNING/MainProcess] /home/ubuntu/.local/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_TRANSPORT_OPTIONS' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_transport_options instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-12 15:28:48,998: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-07-12 15:28:49,159: INFO/MainProcess] Connected to sqs://AKIAWTJBD4D6DM3TMQBC:**@sqs.ca-central-1.amazonaws.com/453725380860/453725380860
[2022-07-12 15:28:49,233: INFO/MainProcess] celery@ip-172-26-3-57 ready.
[2022-07-12 15:29:57,094: INFO/MainProcess] Task ev_flask_functions.parseSendEmail[095b37f2-cf4e-4e1a-a6aa-5122e1ad72eb] received
[2022-07-12 15:29:57,124: WARNING/ForkPoolWorker-1] No ev_api_key.json in CONFIG_DIR file found
[2022-07-12 15:29:57,124: WARNING/ForkPoolWorker-1] 0/5 0.0%
[2022-07-12 15:29:58,077: WARNING/ForkPoolWorker-1] 1/5 20.0%
[2022-07-12 15:29:58,467: WARNING/ForkPoolWorker-1] 2/5 40.0%
[2022-07-12 15:29:59,010: WARNING/ForkPoolWorker-1] 3/5 60.0%
[2022-07-12 15:29:59,833: WARNING/ForkPoolWorker-1] 4/5 80.0%
[2022-07-12 15:30:00,086: ERROR/ForkPoolWorker-1] Task ev_flask_functions.parseSendEmail[095b37f2-cf4e-4e1a-a6aa-5122e1ad72eb] raised unexpected: KeyError('status')
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/lightyear/flask_app/scripts/create_flask_app.py", line 31, in __call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/lightyear/flask_app/scripts/EmailValidator/ev_flask_functions.py", line 84, in parseSendEmail
    emailVerify(path, recipients)
  File "/home/ubuntu/lightyear/flask_app/scripts/EmailValidator/ev_flask_functions.py", line 66, in emailVerify
    email.validation(save=True)
  File "/home/ubuntu/lightyear/flask_app/scripts/EmailValidator/ev_API.py", line 92, in validation
    if self.check(data["Email(s)"][i]) == 'invalid':
  File "/home/ubuntu/lightyear/flask_app/scripts/EmailValidator/ev_API.py", line 82, in check
    return response.json()['status']
KeyError: 'status'
